server:
  port: 8080
  error:
    include-message: always

spring:
  application:
    name: "cc_challenge"

  h2:
    console.enabled: true
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.xml